#!/usr/bin/env python3
"""Verify that a client which never reads is removed without blocking healthy clients.

Start the server first, then run:

    python3 scripts/slow_client_test.py
"""

from __future__ import annotations

import argparse
import os
import socket
import threading
import time


def receive_until(sock: socket.socket, marker: bytes, timeout: float) -> bytes:
    deadline = time.monotonic() + timeout
    received = bytearray()
    while marker not in received:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError(f"timed out waiting for {marker!r}")
        sock.settimeout(remaining)
        chunk = sock.recv(65536)
        if not chunk:
            raise ConnectionError("server closed the connection")
        received.extend(chunk)
    return bytes(received)


def connect_named(
    host: str,
    port: int,
    name: str,
    timeout: float,
    receive_buffer: int | None = None,
) -> socket.socket:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        if receive_buffer is not None:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, receive_buffer)
        sock.settimeout(timeout)
        sock.connect((host, port))
        receive_until(sock, b"Please input your name:", timeout)
        sock.sendall(name.encode() + b"\n")
        receive_until(sock, b"enters the ChatRoom", timeout)
        return sock
    except Exception:
        sock.close()
        raise


def drain_socket(
    sock: socket.socket,
    stop_event: threading.Event,
    errors: list[Exception],
) -> None:
    sock.settimeout(0.2)
    try:
        while not stop_event.is_set():
            try:
                if not sock.recv(65536):
                    raise ConnectionError("healthy client was disconnected")
            except socket.timeout:
                continue
    except Exception as error:
        if not stop_event.is_set():
            errors.append(error)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ChatRoomProject slow-client test")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--messages", type=int, default=256)
    parser.add_argument("--payload-size", type=int, default=32768)
    parser.add_argument("--timeout", type=float, default=5.0)
    parser.add_argument("--settle", type=float, default=1.0)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.messages <= 0 or not 1 <= args.payload_size <= 60000:
        print("messages must be positive; payload-size must be between 1 and 60000")
        return 2

    suffix = str(os.getpid())
    slow_name = f"slow_{suffix}"
    healthy_name = f"healthy_{suffix}"
    slow: socket.socket | None = None
    healthy: socket.socket | None = None
    stop_event = threading.Event()
    reader: threading.Thread | None = None
    reader_errors: list[Exception] = []

    try:
        slow = connect_named(
            args.host,
            args.port,
            slow_name,
            args.timeout,
            receive_buffer=4096,
        )
        healthy = connect_named(
            args.host,
            args.port,
            healthy_name,
            args.timeout,
        )

        reader = threading.Thread(
            target=drain_socket,
            args=(healthy, stop_event, reader_errors),
            daemon=True,
        )
        reader.start()

        payload = b"x" * args.payload_size
        started = time.monotonic()
        for index in range(args.messages):
            healthy.sendall(
                b"slow-client-test " + str(index).encode() + b" " + payload + b"\n"
            )

        time.sleep(args.settle)
        stop_event.set()
        reader.join(timeout=2)
        if reader_errors:
            raise reader_errors[0]

        healthy.sendall(b"/list\n")
        member_list = receive_until(healthy, b"Online users:", args.timeout)
        if b"\n" not in member_list[member_list.rfind(b"Online users:") :]:
            member_list += receive_until(healthy, b"\n", args.timeout)

        list_line = member_list[member_list.rfind(b"Online users:") :].split(b"\n", 1)[0]
        if slow_name.encode() in list_line:
            raise RuntimeError("slow client is still present after its send queue exceeded the limit")
        if healthy_name.encode() not in list_line:
            raise RuntimeError("healthy client disappeared during the slow-client test")

        elapsed = time.monotonic() - started
        total_bytes = args.messages * args.payload_size
        print("Slow-client protection test passed")
        print(f"  generated bytes: {total_bytes}")
        print(f"  messages:        {args.messages}")
        print(f"  elapsed:         {elapsed:.2f}s")
        print(f"  removed client:  {slow_name}")
        print(f"  healthy client:  {healthy_name}")
        return 0
    except Exception as error:
        print(f"Slow-client protection test failed: {error}")
        return 1
    finally:
        stop_event.set()
        if reader is not None:
            reader.join(timeout=1)
        for sock in (healthy, slow):
            if sock is None:
                continue
            try:
                sock.sendall(b"/quit\n")
            except OSError:
                pass
            sock.close()


if __name__ == "__main__":
    raise SystemExit(main())
